### ISSUE TITLE
undefined reference to symbol '_ZN5boost6system15system_categoryEv'

### ISSUE THREAD

**Issue by yoursunny** [pollere/DNMP-v2#2]
Environment:

* Ubuntu 18.04
* ndn-ind commit dd934a7a5106cda6ea14675554427e12df1ce18f
* DNMP-v2 commit c9431460f85c326a410758aa4ff2a26bfcf0df69
* `liblog4cxx-dev libprotobuf-dev protobuf-compiler` are installed before compiling ndn-ind, as this repository seems to require these
* Compiler: `clang++-8`

There's an error in linking step:

```shell
clang++-8 -g -O0 -I. -Wall -std=c++17 -I/usr/local/include -o getStatus getStatus.cpp syncps/syncps-content.pb.o -L/usr/local/lib -lndn-ind -lboost_iostreams -lboost_chrono -lprotobuf -llog4cxx -lpthread
/usr/bin/ld: /tmp/getStatus-5ca876.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The error is caused by this line:
https://github.com/pollere/DNMP-v2/blob/c9431460f85c326a410758aa4ff2a26bfcf0df69/Makefile#L23

It should be changed to:
```
LIBS += -lboost_iostreams -lboost_chrono -lboost_system -lprotobuf -llog4cxx -lpthread
```

**Comment by kmnichols** [comment]
We are unable to reproduce this in our environment: ubuntu 20.10, clang-11/gcc-10 and boost-1.71. Suggest you upgrade and try again?
