### ISSUE TITLE
log4cxx: No appender could be found for logger (syncps.SyncPubsub).

### ISSUE THREAD

**Issue by yoursunny** [pollere/DNMP-v2#3]
Environment:

* Ubuntu 18.04
* ndn-ind commit dd934a7a5106cda6ea14675554427e12df1ce18f
* DNMP-v2 commit c9431460f85c326a410758aa4ff2a26bfcf0df69
* `liblog4cxx-dev libprotobuf-dev protobuf-compiler` are installed before compiling ndn-ind, as this repository seems to require these
* Compiler: `clang++-8`

When I attempt to launch any program, there's an error message:

```
$ ./nod
log4cxx: No appender could be found for logger (syncps.SyncPubsub).
log4cxx: Please initialize the log4cxx system properly.
```

To fix this error, it is necessary to invoke `INIT_LOGGERS()` at the beginning of `main()` function in each program, so that a basic console appender would be configured.

https://github.com/operantnetworks/ndn-ind/blob/dd934a7a5106cda6ea14675554427e12df1ce18f/src/util/logging.cpp#L52-L71

**Comment by kmnichols** [comment]
Added INIT_LOGGERS() to three files with main() functions.
