### ISSUE TITLE
Node::RegisterResponse::operator(): Error in onRegisterFailed

### ISSUE THREAD

**Issue by yoursunny** [pollere/DNMP-v2#4]
Environment:

* Ubuntu 18.04
* ndn-ind commit dd934a7a5106cda6ea14675554427e12df1ce18f
* DNMP-v2 commit c9431460f85c326a410758aa4ff2a26bfcf0df69
* `liblog4cxx-dev libprotobuf-dev protobuf-compiler` are installed before compiling ndn-ind, as this repository seems to require these
* Compiler: `clang++-8`
* NFD 0.7.1 installed from PPA, unpatched

When I attempt to launch any program (e.g. `./nod`), there's an error message:

```
16:34:06 ERROR SyncPubsub - onRegisterFailed /localhost/dnmp
16:34:06 ERROR Node - Node::RegisterResponse::operator(): Error in onRegisterFailed: onRegisterFailed /localhost/dnmp
16:34:06 ERROR SyncPubsub - onRegisterFailed /localnet/dnmp/all
16:34:06 ERROR Node - Node::RegisterResponse::operator(): Error in onRegisterFailed: onRegisterFailed /localnet/dnmp/all
16:34:06 ERROR SyncPubsub - onRegisterFailed /localnet/dnmp/pid869_sunny5
16:34:06 ERROR Node - Node::RegisterResponse::operator(): Error in onRegisterFailed: onRegisterFailed /localnet/dnmp/pid869_sunny5
```

NFD log says:

```
1609364044.155467  WARN: [nfd.GenericLinkService] [id=259,local=unix:///run/nfd.sock,remote=fd://25] packet parse error (Unrecognized element of critical type 9): DROP
1609364044.155525  WARN: [nfd.GenericLinkService] [id=259,local=unix:///run/nfd.sock,remote=fd://25] packet parse error (Unrecognized element of critical type 9): DROP
1609364044.155552  WARN: [nfd.GenericLinkService] [id=259,local=unix:///run/nfd.sock,remote=fd://25] packet parse error (Unrecognized element of critical type 9): DROP
```

TLV-TYPE 0x09 is the assignment of `Selectors` field that belongs to an obsolete packet format no longer supported by NFD.

To solve this problem, it's necessary to add the following in each program:

```cpp
#include <ndn-ind/encoding/tlv-0_3-wire-format.hpp>

// at the top of main() function
ndn::WireFormat::setDefaultWireFormat(ndn::Tlv0_3WireFormat::get());
```

**Comment by kmnichols** [comment]
Thank you for catching this. We believe the main issue is that ndn-ind has version 0.2 as a default and changed this in our local version of ndn-ind (by changing it in two places in the tlv-wire-format.hpp include) and things seem to run properly and no longer put out the selectors. I've asked Operant folks to update the ndn-ind distribution. That should be a better solution.
